{% set name = "arcos-gui" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arcos_gui-{{ version }}.tar.gz
  sha256: a0ec583bf32ef70163bb21a9e98d40bc3ea8bc84569c05c653fae463ba88d278

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - arcos4py >=0.1.4
    - magicgui >=0.3.0
    - matplotlib-base >=3.3.4
    - napari >=0.4.14
    - numpy >=1.21.5
    - pandas >=1.3.5
    - python >=3.8
    - scikit-image >=0.18.1
    - scipy >=1.7.3

test:
  imports:
    - arcos_gui
    - arcos_gui._arcos_widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bgraedel/arcos-gui
  summary: A napari plugin to detect and visualize collective signaling events
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgraedel
    - goanpeca
    - jaimergp
